Repository storybookjs/addon-knobs, pull requests merged in 2023-04, with the labels that each got.

#48 Support Storybook 7.0.0
  .storybook/main.js
  jest.config.js
  package.json
  scripts/jest.init.js
  src/KnobManager.ts
  src/KnobStore.ts
  src/components/Panel.test.tsx
  src/components/Panel.tsx
  src/components/types/Array.test.tsx
  src/components/types/Files.tsx
  src/components/types/Options.tsx
  src/index.ts
  src/register.tsx
  src/registerKnobs.ts
  tsconfig.json
  yarn.lock
Labels: major, dependencies

#49 Upgrade Node in CI
  .github/workflows/release.yml
  .github/workflows/tests-unit.yml
  README.md
Labels: internal

#50 Remove unnecessary `check-metadata.js`
  check-metadata.js
  package.json
Labels: internal

#45 [Hotfix] Seeing knobs from previously selected story
  src/registerKnobs.ts
Labels: bug, patch

#51 build: make storybook peer dependency less strict
  package.json
Labels: patch, dependencies
